default:
  consortium_fileview: "syn21027019"
  samples_table: "syn21578908"
  annotations_storage: "syn21703007"
  annotations_table: "syn10242922"
  annotations_link: "https://shinypro.synapse.org/users/nsanati/annotationUI/"
  annotation_keys:
    - "age"
    - "primaryDiagnosis"
  teams:
    - "273957"
  templates:
    manifest_template: "syn20820080"
    individual_templates:
      human: "syn12973254"
      mouse or other animal model: "syn12973253"
    biospecimen_templates:
      human: "syn12973252"
      mouse or other animal model: "syn12973252"
      drosophila: "syn20673251"
    assay_templates:
      rnaSeq: "syn12973256"
      proteomics: "syn12973255"
  species_list:
    - "mouse or other animal model"
    - "human"
    - "drosophila"
  complete_columns:
    manifest:
      - "parent"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"

amp-ad:
  annotations_link: "https://shinypro.synapse.org/users/kwoo/amp-ad-metadata-dictionary/"
  consortium_fileview: "syn21448475"
  samples_table: "syn21578908"
  annotations_storage: "syn21698384"
  annotations_table: "syn10242922"
  annotation_keys:
    - "age"
    - "primaryDiagnosis"
  teams:
    - "3346847"
  species_list:
    - "human"
    - "drosophila"
    - "MODEL-AD mouse model"
    - "other mouse or animal model"
  templates:
    individual_templates:
      human: "syn12973254"
      other mouse or animal model: "syn12973253"
      MODEL-AD mouse model: "syn21084071"
    biospecimen_templates:
      human: "syn12973252"
      other mouse or animal model: "syn12973252"
      MODEL-AD mouse model: "syn12973252"
      drosophila: "syn20673251"
    assay_templates:
      ATACseq: "syn22024364"
      autorad: "syn22087295"
      immunoassay: "syn22117582"
      proteomics: "syn12973255"
      single cell RNAseq: "syn21018360"
      wholeGenomeSeq: "syn21018358"
      wholeExomeSeq: "syn21078272"
      NanoString: "syn21082744"
      snpArray: "syn21372586"
      TMT quantitation: "syn21433357"
      methylationArray: "syn22036881"
      MRI: "syn22087332"
      PET: "syn22087299"
      16SrRNAseq: "syn24184375"
      metabolomics: "syn24216748"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"

pec:
  samples_table: "syn22175287"
  annotations_table: "syn20981788"
  annotations_storage: "syn21763155"
  annotations_link: "https://www.synapse.org/#!Synapse:syn20729790"
  annotation_keys:
    - "age"
    - "primaryDiagnosis"
  consortium_fileview: "syn21560413"
  teams:
    - "3328037"
  templates:
    manifest_template: "syn20782058"
    individual_templates:
      human: "syn20781820"
      animal model: "syn21053116"
    biospecimen_templates:
      animal model: "syn20768131"
      human: "syn20768131"
    assay_templates:
      wholeGenomeSeq: "syn20980993"
      rnaSeq: "syn20768650"
      ATACSeq: "syn20768526"
      TMT quantitation: "syn21680761"
      HI-C: "syn21680758"
      snpArray: "syn21680759"
      ChIPSeq: "syn21861858"
      bisulfiteSeq: "syn23017098"
  species_list:
    - "human"
    - "animal model"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
    individual:
      - "individualID"
      - "individualIdSource"
      - "species"
      - "reportedGender"
      - "postmortem"
      - "primaryDiagnosis"
    biospecimen:
      - "individualID"
      - "specimenID"
      - "organ"
      - "tissue"
      - "nucleicAcidSource"
    assay:
      - "specimenID"
      - "platform"
      - "libraryPrep"
      - "libraryPreparationMethod"
      - "runType"
